version: 0.1
phases:
  build:
    commands:
      - echo "**** Starting build"
      - echo "**** Running tests"
      - cd tests ; pytest -v -s
#      - echo "**** Deploying Lambda"
#      - cd deploy ; pytest -v -s


#  post_build:
#    commands:

      # coveralls seem to need git installed
      #- cd tests && pytest -v --cov
      #- cp tests/.coverage .
      #- coveralls